export const shopObjOne = {
    id: 'shop1',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Glare',
    headlineviolet: '',
    headline: 'Shop',
    description: '',
    description1: 'our smart mirror will help you follow the daily beauty trend.',
    description2: '',
    description3: '',
    description4: '',
    description5: '',
    description6: '',
    buttonLabel: 'buy',
    buttonLabel2: 'how to',
    imgStart: false,
    img: require('../../images/shop/shop-1.png'),
    alt: 'shop1',
    dark: true,
    primary: true,
    darkText: false
};

export const shopObjTwo = {
    id: 'shop2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Beauty Products',
    headlineviolet: '',
    headline: '',
    description: '',
    description1: 'buy our latest products',
    description2: 'to achieve the best trend look',
    description3: '',
    description4: '',
    description5: '',
    description6: '',
    buttonLabel: 'buy',
    buttonLabel2: 'explore',
    imgStart: false,
    img: require('../../images/shop/shop-2.png'),
    alt: 'shop2',
    dark: true,
    primary: true,
    darkText: false
};