export const homeObjOne = {
    id: 'ourfocus',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: '',
    headlineviolet: 'Our',
    headline: 'Focus',
    description: '',
    description1: 'we are the new frontier of beauty,',
    description2: 'with our powerful technologies,',
    description3: 'we will guide you through a journey for etherealness.',
    description4: 'let our ',
    description5: '*mirror*',
    description6: ' lead you to be the best version of yourself everyday.',
    //buttonLabel: 'learn more',
    imgStart: true,
    img: require('../../images/hero/scwhachrome.png'),
    //require('../../images/svg1.svg').default,
    alt: '',
    dark: true,
    primary: true,
    darkText: true
};

export const homeObjTwo = {
    id: 'trend',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: '',
    headlineviolet: 'Trend',
    headline: 'Board',
    description: '',
    description1: '',
    description2: '',
    description3: 'be the best version of your self,',
    description4: 'follow the ',
    description5: 'trend',
    description6: '',
    //buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/trendboard/trendboard.png'),
    alt: '',
    dark: false,
    primary: false,
    darkText: true
};

export const homeObjThree = {
    id: 'you',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: '',
    headlineviolet: 'You.',
    headline: '',
    description: '',
    description1: '',
    description2: 'frase in cui mettiamo in risalto you',
    description3: '',
    description4: 'connect your glare in your ',
    description5: 'personal area',
    description6: '',
    description7: "if you have any questions ",
    description8: 'contact us',
    description9: '',
    //buttonLabel: 'Start Now',
    imgStart: false,
    img: '',
    alt: '',
    dark: false,
    primary: false,
    darkText: true
};